static const char   *countries[][2] = {
    { "[Codes]", "" },
    { "US", "United States" },
    { "ZZ", "Other" },
    { "AF", "Afghanistan" },
    { "AL", "Albania" },
    { "DZ", "Algeria" },
    { "AS", "American Samoa" },
    { "AD", "Andorra" },
    { "AO", "Angola" },
    { "AI", "Anguilla" },
    { "AQ", "Antarctica" },
    { "AG", "Antigua and Barbuda" },
    { "AR", "Argentina" },
    { "AM", "Armenia" },
    { "AW", "Aruba" },
    { "AU", "Australia" },
    { "AT", "Austria" },
    { "AZ", "Azerbaijan" },
    { "BS", "Bahamas" },
    { "BH", "Bahrain" },
    { "BD", "Bangladesh" },
    { "BB", "Barbados" },
    { "BY", "Belarus" },
    { "BE", "Belgium" },
    { "BZ", "Belize" },
    { "BJ", "Benin" },
    { "BM", "Bermuda" },
    { "BT", "Bhutan" },
    { "BO", "Bolivia" },
    { "BA", "Bosnia and Herzegovina" },
    { "BW", "Botswana" },
    { "BV", "Bouvet Island" },
    { "BR", "Brazil" },
    { "IO", "British Indian Ocean Territory" },
    { "BN", "Brunei Darussalam" },
    { "BG", "Bulgaria" },
    { "BF", "Burkina Faso" },
    { "BI", "Burundi" },
    { "KH", "Cambodia" },
    { "CM", "Cameroon" },
    { "CA", "Canada" },
    { "CV", "Cape Verde" },
    { "CT", "Catalonia" },
    { "KY", "Cayman Islands" },
    { "CF", "Central African Republic" },
    { "TD", "Chad" },
    { "CL", "Chile" },
    { "CN", "China" },
    { "CX", "Christmas Island" },
    { "CC", "Cocos (Keeling Islands)" },
    { "CO", "Colombia" },
    { "KM", "Comoros" },
    { "CG", "Congo" },
    { "CK", "Cook Islands" },
    { "CR", "Costa Rica" },
    { "CI", "Cote D'Ivoire (Ivory Coast)" },
    { "HR", "Croatia (Hrvatska)" },
    { "CU", "Cuba" },
    { "CY", "Cyprus" },
    { "CZ", "Czech Republic" },
    { "DK", "Denmark" },
    { "DJ", "Djibouti" },
    { "DM", "Dominica" },
    { "DO", "Dominican Republic" },
    { "TP", "East Timor" },
    { "EC", "Ecuador" },
    { "EG", "Egypt" },
    { "SV", "El Salvador" },
    { "GQ", "Equatorial Guinea" },
    { "ER", "Eritrea" },
    { "EE", "Estonia" },
    { "ET", "Ethiopia" },
    { "FK", "Falkland Islands (Malvinas)" },
    { "FO", "Faroe Islands" },
    { "FJ", "Fiji" },
    { "FI", "Finland" },
    { "FR", "France" },
    { "FX", "France Metropolitan" },
    { "GF", "French Guiana" },
    { "PF", "French Polynesia" },
    { "TF", "French Southern Territories" },
    { "GA", "Gabon" },
    { "GM", "Gambia" },
    { "GE", "Georgia" },
    { "DE", "Germany" },
    { "GH", "Ghana" },
    { "GI", "Gibraltar" },
    { "GR", "Greece" },
    { "GL", "Greenland" },
    { "GD", "Grenada" },
    { "GP", "Guadeloupe" },
    { "GU", "Guam" },
    { "GT", "Guatemala" },
    { "GN", "Guinea" },
    { "GW", "Guinea-Bissau" },
    { "GY", "Guyana" },
    { "HT", "Haiti" },
    { "HM", "Heard and McDonald Islands" },
    { "HN", "Honduras" },
    { "HK", "Hong Kong" },
    { "HU", "Hungary" },
    { "IS", "Iceland" },
    { "IN", "India" },
    { "ID", "Indonesia" },
    { "IR", "Iran" },
    { "IQ", "Iraq" },
    { "IE", "Ireland" },
    { "IL", "Israel" },
    { "IT", "Italy" },
    { "JM", "Jamaica" },
    { "JP", "Japan" },
    { "JO", "Jordan" },
    { "KZ", "Kazakhstan" },
    { "KE", "Kenya" },
    { "KI", "Kiribati" },
    { "KP", "North Korea" },
    { "KR", "South Korea" },
    { "KW", "Kuwait" },
    { "KG", "Kyrgyzstan" },
    { "LA", "Laos" },
    { "LV", "Latvia" },
    { "LB", "Lebanon" },
    { "LS", "Lesotho" },
    { "LR", "Liberia" },
    { "LY", "Libya" },
    { "LI", "Liechtenstein" },
    { "LT", "Lithuania" },
    { "LU", "Luxembourg" },
    { "MO", "Macau" },
    { "MK", "Macedonia" },
    { "MG", "Madagascar" },
    { "MW", "Malawi" },
    { "MY", "Malaysia" },
    { "MV", "Maldives" },
    { "ML", "Mali" },
    { "MT", "Malta" },
    { "MH", "Marshall Islands" },
    { "MQ", "Martinique" },
    { "MR", "Mauritania" },
    { "MU", "Mauritius" },
    { "YT", "Mayotte" },
    { "MX", "Mexico" },
    { "FM", "Micronesia" },
    { "MD", "Moldova" },
    { "MC", "Monaco" },
    { "MN", "Mongolia" },
    { "MS", "Montserrat" },
    { "MA", "Morocco" },
    { "MZ", "Mozambique" },
    { "MM", "Myanmar (Burma)" },
    { "NA", "Namibia" },
    { "NR", "Nauru" },
    { "NP", "Nepal" },
    { "NL", "Netherlands" },
    { "AN", "Netherlands Antilles" },
    { "NC", "New Caledonia" },
    { "NZ", "New Zealand" },
    { "NI", "Nicaragua" },
    { "NE", "Niger" },
    { "NG", "Nigeria" },
    { "NU", "Niue" },
    { "NF", "Norfolk Island" },
    { "MP", "Northern Mariana Islands" },
    { "NO", "Norway" },
    { "OM", "Oman" },
    { "PK", "Pakistan" },
    { "PW", "Palau" },
    { "PA", "Panama" },
    { "PG", "Papua New Guinea" },
    { "PY", "Paraguay" },
    { "PE", "Peru" },
    { "PH", "Philippines" },
    { "PN", "Pitcairn" },
    { "PL", "Poland" },
    { "PT", "Portugal" },
    { "PR", "Puerto Rico" },
    { "QA", "Qatar" },
    { "RE", "Reunion" },
    { "RO", "Romania" },
    { "RU", "Russian Federation" },
    { "RW", "Rwanda" },
    { "KN", "Saint Kitts and Nevis" },
    { "LC", "Saint Lucia" },
    { "VC", "Saint Vincent and The Grenadines" },
    { "WS", "Samoa" },
    { "SM", "San Marino" },
    { "ST", "Sao Tome and Principe" },
    { "SA", "Saudi Arabia" },
    { "SN", "Senegal" },
    { "SC", "Seychelles" },
    { "SL", "Sierra Leone" },
    { "SG", "Singapore" },
    { "SK", "Slovak Republic" },
    { "SI", "Slovenia" },
    { "SB", "Solomon Islands" },
    { "SO", "Somalia" },
    { "ZA", "South Africa" },
    { "GS", "S. Georgia and S. Sandwich Isls." },
    { "ES", "Spain" },
    { "LK", "Sri Lanka" },
    { "SH", "St. Helena" },
    { "PM", "St. Pierre and Miquelon" },
    { "SD", "Sudan" },
    { "SR", "Suriname" },
    { "SJ", "Svalbard and Jan Mayen Islands" },
    { "SZ", "Swaziland" },
    { "SE", "Sweden" },
    { "CH", "Switzerland" },
    { "SY", "Syria" },
    { "TW", "Taiwan" },
    { "TJ", "Tajikistan" },
    { "TZ", "Tanzania" },
    { "TH", "Thailand" },
    { "TG", "Togo" },
    { "TK", "Tokelau" },
    { "TO", "Tonga" },
    { "TT", "Trinidad and Tobago" },
    { "TN", "Tunisia" },
    { "TR", "Turkey" },
    { "TM", "Turkmenistan" },
    { "TC", "Turks and Caicos Islands" },
    { "TV", "Tuvalu" },
    { "UG", "Uganda" },
    { "UA", "Ukraine" },
    { "AE", "United Arab Emirates" },
    { "UK", "United Kingdom" },
    { "UM", "US Minor Outlying Islands" },
    { "UY", "Uruguay" },
    { "UZ", "Uzbekistan" },
    { "VU", "Vanuatu" },
    { "VA", "Vatican City" },
    { "VE", "Venezuela" },
    { "VN", "VietNam" },
    { "VG", "Virgin Islands (British)" },
    { "VI", "Virgin Islands (US)" },
    { "WF", "Wallis and Futuna Islands" },
    { "EH", "Western Sahara" },
    { "YE", "Yemen" },
    { "YU", "Yugoslavia" },
    { "ZR", "Zaire" },
    { "ZM", "Zambia" },
    { "ZW", "Zimbabwe" },
    { "", "" },
    { "[USStates]", "" },
    { "01", "Alabama " },
    { "02", "Alaska " },
    { "04", "Arizona " },
    { "05", "Arkansas " },
    { "06", "California " },
    { "08", "Colorado " },
    { "09", "Connecticut " },
    { "10", "Delaware " },
    { "11", "Dist. of Columbia " },
    { "12", "Florida " },
    { "13", "Georgia " },
    { "15", "Hawaii " },
    { "16", "Idaho " },
    { "17", "Illinois " },
    { "18", "Indiana " },
    { "19", "Iowa " },
    { "20", "Kansas " },
    { "21", "Kentucky " },
    { "22", "Louisiana " },
    { "23", "Maine " },
    { "24", "Maryland " },
    { "25", "Massachusetts " },
    { "26", "Michigan " },
    { "27", "Minnesota " },
    { "28", "Mississippi " },
    { "29", "Missouri " },
    { "30", "Montana " },
    { "31", "Nebraska " },
    { "32", "Nevada " },
    { "33", "New Hampshire " },
    { "34", "New Jersey " },
    { "35", "New Mexico " },
    { "36", "New York " },
    { "37", "North Carolina " },
    { "38", "North Dakota " },
    { "39", "Ohio " },
    { "40", "Oklahoma " },
    { "41", "Oregon " },
    { "42", "Pennsylvania " },
    { "44", "Rhode Island " },
    { "45", "South Carolina " },
    { "46", "South Dakota " },
    { "47", "Tennessee " },
    { "48", "Texas " },
    { "49", "Utah " },
    { "50", "Vermont " },
    { "51", "Virginia " },
    { "53", "Washington " },
    { "54", "West Virginia " },
    { "55", "Wisconsin " },
    { "56", "Wyoming " },
    { "60", "American Samoa " },
    { "64", "Micronesia " },
    { "66", "Guam " },
    { "68", "Marshall Islands " },
    { "69", "No. Mariana Islands  " },
    { "70", "Palau " },
    { "72", "Puerto Rico " },
    { "74", "U.S. Islands" },
    { "78", "Virgin Islands" },
    { NULL, NULL }
};
